spring:
 datasource:
   driver-class-name:  com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://trainingdb.ck1ayq0lncmp.ap-south-1.rds.amazonaws.com:3306/charityapp_donor_db
   username: pradeepa
   password: pradeepa
flyway:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://trainingdb.ck1ayq0lncmp.ap-south-1.rds.amazonaws.com:3306/charityapp_donor_db
   username: pradeepa
   password: pradeepa